exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprshell run &
exec-once = sleep 1 && waybar
exec-once = swayosd-server
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hypridle
exec-once = hyprpaper
exec-once = mako
exec-once = snappy-switcher --daemon
