# Application bindings
bind = SUPER, Space, exec, float-run-foot launcher
bind = SUPER, RETURN, exec, foot
bind = SUPER, B, exec, chromium

#Shortcut rebinding to make like mac
bind = SUPER, C, sendshortcut, CTRL, Insert, active
bind = SUPER, V, sendshortcut, SHIFT, Insert, active
bind = SUPER, X, sendshortcut, CTRL, X, active
bind = SUPER, A, sendshortcut, CTRL, A, active
bind = SUPER, T, sendshortcut, CTRL, T, active
bind = SUPER, Z, sendshortcut, CTRL, Z, active
bind = SUPER, S, sendshortcut, CTRL, S, active
bind = SUPER, W, sendshortcut, CTRL, W, active
bind = SUPER, R, sendshortcut, CTRL, R, active
bind = SUPER, L, sendshortcut, CTRL, L, active
bind = SUPER, 1, sendshortcut, CTRL, 1, active
bind = SUPER, 2, sendshortcut, CTRL, 2, active
bind = SUPER, 3, sendshortcut, CTRL, 3, active
bind = SUPER, 4, sendshortcut, CTRL, 4, active
bind = SUPER, 5, sendshortcut, CTRL, 5, active
bind = SUPER, 6, sendshortcut, CTRL, 6, active
bind = SUPER, 7, sendshortcut, CTRL, 7, active
bind = SUPER, 8, sendshortcut, CTRL, 8, active
bind = SUPER, 9, sendshortcut, CTRL, 9, active

# Only display the OSD on the currently focused monitor
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"

# Laptop multimedia keys for volume and LCD brightness (with OSD)
bindeld = ,XF86AudioRaiseVolume, Volume up, exec, $osdclient --output-volume raise
bindeld = ,XF86AudioLowerVolume, Volume down, exec, $osdclient --output-volume lower
bindeld = ,XF86AudioMute, Mute, exec, $osdclient --output-volume mute-toggle
bindeld = ,XF86AudioMicMute, Mute microphone, exec, $osdclient --input-volume mute-toggle
bindeld = ,XF86MonBrightnessUp, Brightness up, exec, $osdclient --brightness raise
bindeld = ,XF86MonBrightnessDown, Brightness down, exec, $osdclient --brightness lower

# Precise 1% multimedia adjustments with Alt modifier
bindeld = ALT, XF86AudioRaiseVolume, Volume up precise, exec, $osdclient --output-volume +1
bindeld = ALT, XF86AudioLowerVolume, Volume down precise, exec, $osdclient --output-volume -1
bindeld = ALT, XF86MonBrightnessUp, Brightness up precise, exec, $osdclient --brightness +1
bindeld = ALT, XF86MonBrightnessDown, Brightness down precise, exec, $osdclient --brightness -1

# Requires playerctl
bindld = , XF86AudioNext, Next track, exec, $osdclient --playerctl next
bindld = , XF86AudioPause, Pause, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPlay, Play, exec, $osdclient --playerctl play-pause
bindld = , XF86AudioPrev, Previous track, exec, $osdclient --playerctl previous

#window binds
bind = SUPER, Q, killactive,
bindd = ALT, H, Move focus left, movefocus, l
bindd = ALT, L, Move focus right, movefocus, r
bindd = ALT, K, Move focus up, movefocus, u
bindd = ALT, J, Move focus down, movefocus, d
bind = ALT, 1, workspace, 1
bind = ALT, 2, workspace, 2
bind = ALT, 3, workspace, 3
bind = ALT, 4, workspace, 4
bind = ALT, 5, workspace, 5
bind = ALT, 6, workspace, 6
bind = ALT, 7, workspace, 7
bind = ALT, 8, workspace, 8
bind = ALT, 9, workspace, 9
bind = ALT SHIFT, 1, movetoworkspace, 1
bind = ALT SHIFT, 2, movetoworkspace, 2
bind = ALT SHIFT, 3, movetoworkspace, 3
bind = ALT SHIFT, 4, movetoworkspace, 4
bind = ALT SHIFT, 5, movetoworkspace, 5
bind = ALT SHIFT, 6, movetoworkspace, 6
bind = ALT SHIFT, 7, movetoworkspace, 7
bind = ALT SHIFT, 8, movetoworkspace, 8
bind = ALT SHIFT, 9, movetoworkspace, 9

#Utility
bindd = SUPER, P, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = , PRINT, Screenshot, exec, screenshot
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bind = SUPER SHIFT, M, exec, hyprctl keyword monitor "eDP-1, disable"
bind = SUPER, M, exec, hyprctl keyword monitor "eDP-1, 3840x2400@60, 0x0, 2.5"
bind = SUPER, Tab, exec, snappy-switcher next --mod super
