env = GDK_SCALE,1.75
monitor= DP-3,2560x1440@60,auto,1.33
monitor = eDP-1, 3840x2400@60, 0x0, 2.5

windowrule = suppress_event maximize, match:class .*
windowrule = opacity 0.97 0.9, match:class .*
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = match:class floating_tui, float on, center on, size 800 500
windowrule {
  name = auto-group
  match:class = .*
  match:workspace = 1
  group = set  # Using 'set' or leaving it blank as per effect description
}

input {
  kb_layout = us
  kb_options = caps:escape, altwin:swap_alt_win
  repeat_rate = 40
  repeat_delay = 600
  numlock_by_default = true
  touchpad {
    scroll_factor = 0.4
  }
}

windowrule = match:class (Alacritty|kitty), scroll_touchpad 1.5
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland

xwayland {
  force_zero_scaling = true
}
