general {
    # This is what loginctl calls. If loginctl fails, we use this directly below.
    lock_cmd = pidof hyprlock || hyprlock       
    before_sleep_cmd = loginctl lock-session    
    after_sleep_cmd = hyprctl dispatch dpms on  
}

# 1. Dim
listener {
    timeout = 280                                
    on-timeout = brightnessctl -s set 10         
    on-resume = brightnessctl -r                
}

# 2. Lock (Direct Call)
listener {
    timeout = 300                                
    on-timeout = pidof hyprlock || hyprlock      
}

# 3. DPMS Off
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch dpms off       
    on-resume = hyprctl dispatch dpms on         
}
