# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# Hyprland 0.53+ syntax
windowrule = suppress_event maximize, match:class .*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
windowrule = match:class floating_tui, float on, center on, size 800 500
windowrule {
  name = auto-group
  match:class = .*
  match:workspace = 1
  group = set  # Using 'set' or leaving it blank as per effect description
}
