# Copy / Paste
bindd = SUPER, C, Universal copy, sendshortcut, CTRL, Insert,
bindd = SUPER, V, Universal paste, sendshortcut, SHIFT, Insert,
bindd = SUPER, X, Universal cut, sendshortcut, CTRL, X,
bindd = SUPER, A, Universal selectall, sendshortcut, CTRL, A,
bind = SUPER, T, sendshortcut, CTRL, T,
bind = SUPER, Z, sendshortcut, CTRL, Z,
bind = SUPER, S, sendshortcut, CTRL, S,
bind = SUPER, W, sendshortcut, CTRL, W,
bind = SUPER, R, sendshortcut, CTRL, R,
bind = SUPER, L, sendshortcut, CTRL, L,
bind = SUPER, 1, sendshortcut, CTRL, 1,
bind = SUPER, 2, sendshortcut, CTRL, 2,
bind = SUPER, 3, sendshortcut, CTRL, 3,
bind = SUPER, 4, sendshortcut, CTRL, 4,
bind = SUPER, 5, sendshortcut, CTRL, 5,
bind = SUPER, 6, sendshortcut, CTRL, 6,
bind = SUPER, 7, sendshortcut, CTRL, 7,
bind = SUPER, 8, sendshortcut, CTRL, 8,
bind = SUPER, 9, sendshortcut, CTRL, 9,
