bindd = SUPER, P, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = , PRINT, Screenshot, exec, screenshot
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
#Turn of laptop display
bind = SUPER SHIFT, M, exec, hyprctl keyword monitor "eDP-1, disable"
bind = SUPER, M, exec, hyprctl keyword monitor "eDP-1, 3840x2400@60, 0x0, 2.5"
